@startuml
用户 <|-- 教师
用户 <|-- 学生
用户 -- 用户状态
专业 "1"--"n" 学生
教师 "1"--"n" 部门
教师 "1"--"n" 课程教师关联
课程 "1"--"n" 课程教师关联
课程 "1"--"n" 课程专业学期关联
专业 "1"--"n" 课程专业学期关联
学期 "1"--"n" 课程专业学期关联
教师 "1"--"n" 实验
课程 "1"--"n" 实验
实验 "1"--"n" 评分标准
总评分 "1"--"n" 详细评分
评分标准 "1"--"n" 详细评分
class 用户{
用户真实姓名
github账户名
密码
修改时间
}
class 教师{

}
class 学生{
年级
班级
}
class 课程{
课程名称
}
class 专业{
专业名称
}
class 学期{
学期名称
学期开始时间
学期结束时间
}
class 部门{
部门名称
}
class 用户状态{
状态名称
}
class 实验{
实验名称
实验描述链接
}
class 总评分{
分数
评语
修改时间
}
class 评分标准{
标准名称
标准描述
标准占比
}
class 详细评分{
分数
评语
修改时间
}
@enduml