@startuml
actor admin as "图书管理员"
participant "系统配置信息" as A
admin->A :查询系统配置信息
activate admin
activate A
A->admin :系统配置信息
deactivate A
deactivate admin
admin->A :设定系统配置信息
activate admin
activate A
A->admin :设定结果
deactivate A
deactivate admin
@enduml